// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qflgmcuyxnvflzglfoon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbGdtY3V5eG52Zmx6Z2xmb29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODY5OTEsImV4cCI6MjA3MDI2Mjk5MX0.YY9Y8f8b7VYPRU8aB1X5tuVPAX63x-KxI1VjQz9xINg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});